### ISSUE TITLE
is there any way to paste picture inside vsc from clipboard then insert it by Anki ?

### ISSUE THREAD

**Issue by abedahmeduhp** [jasonwilliams/anki#21]

**Comment by ThrashAbaddon** [comment]
This interests me also

**Comment by jasonwilliams** [comment]
Could you go into more detail on what you want to happen here? Which card does the picture go to? Is this pasting into a markdown file or straight into a new VSCode file? I’ve never pasted an image directly into code so don’t understand this workflow

**Comment by Stedag** [comment]
Search for packages in vscode related to pasting images. https://github.com/imlinhanchao/vsc-markdown-image works well. It will embed the image into your markdown file and store the image in a specified directory.

Assuming vscodeanki handles the link properly, this should be all you need. 👍

**Comment by jasonwilliams** [comment]
@Stedag would you be up for working on this?

**Comment by Stedag** [comment]
This feature is available through the marketplace.

@abedahmeduhp and @ThrashAbaddon  I tested images pasted with [Markdown Image](https://marketplace.visualstudio.com/items?itemName=hancel.markdown-image) are incorporated properly. It works great so far:

![image](https://user-images.githubusercontent.com/5147273/100146712-53a91b00-2e68-11eb-80ca-9f0b3529fb6c.png)
-becomes->
![image](https://user-images.githubusercontent.com/5147273/100146762-63c0fa80-2e68-11eb-9c23-734cb2f426d5.png)
---
@jasonwilliams you can probably close the issue unless you're hoping to incorporate these features into VScodeAnki.

I am very interested in working on #18 because I use LaTeX. Unfortunately I am new to regex, javascript, and extension development so I'm going to try a [workaround in python](https://github.com/Stedag/anki_tex) first. If someone is willing to provide some direction as to where I would place a search & replace function within the extension that would possibly help me along... I'll continue this discussion at that issue.

**Comment by jasonwilliams** [comment]
This sounds good to me, I’m closing 
@Stedag please ask me questions in that issue I can help, I’ll also write a contributing guide and ping you that too
