### ISSUE TITLE
Need rewrite deck card！

### ISSUE THREAD

**Issue by snake89322** [jasonwilliams/anki#31]
new  markdown and use “send to deck”， it's ok！
but then I modify the markdown，same title，then “send to deck”，no changes in Anki.

```markdown
## Foo

bar
```
send to deck  -  OK!

---------------------------------

```markdown(same)
## Foo

bar change
```
send to deck  -  not changes!

How can I rewirte the same card?

**Comment by jasonwilliams** [comment]
Hi @snake89322 thanks for raising.
Rewriting functionality currently doesn’t exist, what you’re seeing happen is the Anki extension preventing you from overwriting a card that already exists.

When I last attempted this it wasn’t easy, but ok leave this open as a feature request and take another look some time

**Comment by fletchermoore** [comment]
@snake89322 

If this happens, would you expect the edited card to retain the spaced repetition information, supposing you already memorized it. Or would you expect to start memorizing it again as a new card?

**Comment by fletchermoore** [comment]
So I was about to send a pull for my allowOverwrite option. I have noticed more than one issue posted here that people want the ability to add duplicates. Since this functionality is contrasting allowOverwrite, they perhaps need to be a toggle.

Possible options would be:
anki.send.duplicateBehavior: toggle
- Delete and replace if backs match
- Update in place, leaving learning metadata unchanged
- Make the duplicates anyway
- Leave things unchanged

**Comment by snake89322** [comment]
I find new API anki-connect:
`updateNoteFields`
https://github.com/FooSoft/anki-connect/blob/master/actions/notes.md  

it works, hopes add in new version soonly! 3ks~

**Comment by searene** [comment]
It would be nice if I could update the front side of the card too. It requires attaching the Anki note id to the question when added:

```markdown
## This is the question
:PROPERTY_ANKI_NOTE_ID: 134141234

This is the answer
```

Thus when I change the question or the answer, `Anki For VSCode` should notice that the card is already added before, the preferable behavior should then be `update` instead of `create`.

This is the idea behind [anki-editor.el](https://github.com/louietan/anki-editor). However, `anki-editor.el` use the `org-mode` syntax, which allows attaching properties to headings. `markdown` doesn't have an official way to do it.

We sometimes do need to modify the question, but currently there's no simple way to do it. I don't have a solution, either. I'm just offering some ideas and hoping it can inspire someone to give a solution.

**Comment by jasonwilliams** [comment]
@searene have a look at the https://github.com/jasonwilliams/anki/issues/33 issue which fleshes out the implementation a bit more and feel free to comment there

**Comment by memeplex** [comment]
Obsidian dataview and Logseq are using the `property:: value` syntax for metadata, see https://blacksmithgu.github.io/obsidian-dataview/data-annotation/. For example:

```
## Really?
anki-id:: 123

Yes
```

or

```
## Really? [anki-id:: 123]

Yes
```

**Comment by jasonwilliams** [comment]
Hey @memeplex thanks for the suggestion, its useful to see how others are doing it. I wonder if frontmatter is the most standard way of doing it so that other markdown viewers don't show the data. Do you know if these inline fields will show up on markdown viewers/editors?

**Comment by memeplex** [comment]
Yes, they probably will, these are conventions more or less adopted by the PKM community, but just that.

The obsidian-spaced-repetition extension uses this syntax `<!--SR:!2022-05-06,3,250-->`. This probably is compatible with every markdown tool out there. Perhaps `<!--ANKI:ID=123-->` ?

**Comment by benjamin-weller** [comment]
@jasonwilliams Would you be willing to accept a PR for this work? Any suggestions on how to get started working on developing this improvement for the extension?

**Comment by jasonwilliams** [comment]
@benjamin-weller PRs are welcome, but I would be willing to hear how you plan to approach this fix too. Whether you want to explain that here or in the PR that’s fine.

As for contributing, you can just check this out and run the debugger in VSCode with Anki also loaded. That’s about it

**Comment by benjamin-weller** [comment]
[See my pull request for parsing note IDs.](https://github.com/jasonwilliams/anki/pull/92)

I intend to further develop here such that you can automatically insert the created note ID beneath the `##/h2`

**Comment by jasonwilliams** [comment]
I also came across https://github.com/EvitanRelta/htmlarkdown which could be useful for converting the rendered HTML back to markdown

**Comment by jasonwilliams** [comment]
I'm wondering if this issue still needs to be open, now that updating cards is now possible https://github.com/jasonwilliams/anki?tab=readme-ov-file#update-cards-beta

**Comment by benjamin-weller** [comment]
Yeah FFT close
